### ISSUE TITLE
Backup fails for bitbucket cause the user check assumes the wrong user

### ISSUE THREAD

**Issue by SidgranisSon** [tokcum/AtlasBck#1]
Hello @tokcum ,
the backup scripts crashes for bitbucket, cause the script assumes that the application user has the same name as the application (e.g. JIRA --> jira), but for bitbucket the default username is not bitbucket, its atlbitbucket. This causes the script to block its execution.

_20200525-1459 FATAL: Running atlasbck as atlbitbucket for application BITBUCKET, has to be done as bitbucket._

The error is located at this line I think. Maybe I find the time to fix it soon.
_https://github.com/tokcum/AtlasBck/blob/17bdb37900485ddaaa17663f58ca572c98f565c1/atlasbck.sh#L125_

Thanks and regards!

**Comment by SidgranisSon** [comment]
The current workaround should be to set the _USER_BITBUCKET_ variable in the _atlasbck.cfg_ file, but this is not the expected behavior if you have a default installation.
Additionally it doesn't work either. But here I have to dig a little deeper before I find the correct solution within the script.

**Comment by tokcum** [comment]
Hi @SidgranisSon,
true, thank you for the bug report. I'm working on it. I'm going to come back to you soon.

**Comment by tokcum** [comment]
Hi @SidgranisSon,
I fixed the issue and tested it with my Bitbucket instance. Please pull the latest commit and confirm. Thank you.

**Comment by SidgranisSon** [comment]
Works perfect! Thank you!
